# Generated by Django 5.2.5 on 2025-08-30 02:38

import datetime
import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('No League', 'Noleague'), ('NFL', 'nfl'), ('NBA', 'nba'), ('MLB', 'mlb')], default='No League', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='sport',
        ),
        migrations.AddField(
            model_name='athlete',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='awards',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='athlete',
            name='birthdate',
            field=models.DateField(default=datetime.date(1500, 1, 1)),
        ),
        migrations.AddField(
            model_name='athlete',
            name='college',
            field=models.CharField(default='No College', max_length=300),
        ),
        migrations.AddField(
            model_name='athlete',
            name='draft',
            field=models.CharField(default='Undrafted', max_length=300),
        ),
        migrations.AddField(
            model_name='athlete',
            name='teams',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(default='Unnamed Athlete', max_length=200),
        ),
        migrations.AddField(
            model_name='athlete',
            name='league',
            field=models.ForeignKey(default=game.models.get_default_league, on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='game.league'),
        ),
        migrations.CreateModel(
            name='mlbStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_app', models.IntegerField(default=0)),
                ('at_bats', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('rbis', models.IntegerField(default=0)),
                ('hrs', models.IntegerField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('tb', models.IntegerField(default=0)),
                ('b_war', models.FloatField(default=0.0)),
                ('batting_avg', models.FloatField(default=0.0)),
                ('on_base_pct', models.FloatField(default=0.0)),
                ('slg', models.FloatField(default=0.0)),
                ('ops', models.FloatField(default=0.0)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mlb_stats', to='game.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='nbaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_game', models.FloatField()),
                ('assists_per_game', models.FloatField()),
                ('rebounds_per_game', models.FloatField()),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nba_stats', to='game.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='nflStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fumbles', models.IntegerField(default=0)),
                ('pass_yds', models.IntegerField(default=0)),
                ('pass_tds', models.IntegerField(default=0)),
                ('pass_ints', models.IntegerField(default=0)),
                ('pass_rtg', models.FloatField(default=0.0)),
                ('qb_rec', models.CharField(max_length=10)),
                ('pass_sks', models.IntegerField(default=0)),
                ('pass_cmps', models.IntegerField(default=0)),
                ('pass_atts', models.IntegerField(default=0)),
                ('pass_cmp_pct', models.FloatField(default=0.0)),
                ('pass_yds_per_att', models.FloatField(default=0.0)),
                ('rush_yds', models.IntegerField(default=0)),
                ('rush_tds', models.IntegerField(default=0)),
                ('rush_atts', models.IntegerField(default=0)),
                ('rush_yds_per_att', models.FloatField(default=0.0)),
                ('rec_yds', models.IntegerField(default=0)),
                ('rec_tds', models.IntegerField(default=0)),
                ('recs', models.IntegerField(default=0)),
                ('solo_tkls', models.IntegerField(default=0)),
                ('comb_tkls', models.IntegerField(default=0)),
                ('def_sks', models.FloatField(default=0.0)),
                ('tfl', models.IntegerField(default=0.0)),
                ('ffmbls', models.IntegerField(default=0)),
                ('fmbl_tds', models.IntegerField(default=0)),
                ('def_ints', models.IntegerField(default=0)),
                ('def_int_tds', models.IntegerField(default=0)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfl_stats', to='game.athlete')),
            ],
        ),
    ]
