# Generated by Django 5.2.5 on 2025-09-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_league_remove_athlete_sport_athlete_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='position',
            field=models.CharField(default='', max_length=10),
        ),
    ]
