# Generated by Django 5.2.5 on 2025-09-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_athlete_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflstats',
            name='rec_yds_per_att',
            field=models.FloatField(default=0),
        ),
    ]
