# Generated by Django 5.2.5 on 2025-09-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_nflstats_rec_yds_per_att'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbstats',
            name='bb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlbstats',
            name='era',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mlbstats',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlbstats',
            name='ip',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mlbstats',
            name='ks',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='mlbstats',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlbstats',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlbstats',
            name='so',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlbstats',
            name='whip',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mlbstats',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(default='Unnamed Athlete', max_length=200, unique=True),
        ),
    ]
